## NOTE SOME FIELD NEEDS TO BE DELETED OR ADDED IN YOUR CASE DEPENDING ON WHICH DATA IS RECORDED
activity = GC.activity()
f = open('D:/git-repos/GoldenCheetah_Python_Chart_Wrapper/GC_DATA/activity_xxx_data.py', "w+")
f.writelines("activity_xxx = {")
f.writelines("'seconds': " + str(list(activity['seconds'])) +", \n")
f.writelines("'cadence': " + str(list(activity['cadence'])) +", \n")
f.writelines("'cadenced': " + str(list(activity['cadenced'])) +", \n")
f.writelines("'heart.rate': " + str(list(activity['heart.rate'])) +", \n")
f.writelines("'heart.rated': " + str(list(activity['heart.rated'])) +", \n")
f.writelines("'distance': " + str(list(activity['distance'])) +", \n")
f.writelines("'speed': " + str(list(activity['speed'])) +", \n")
f.writelines("'acceleration': " + str(list(activity['acceleration'])) +", \n")
f.writelines("'power': " + str(list(activity['power'])) +", \n")
f.writelines("'powerd': " + str(list(activity['powerd'])) +", \n")
f.writelines("'altitude': " + str(list(activity['altitude'])) +", \n")
f.writelines("'longitude': " + str(list(activity['longitude'])) +", \n")
f.writelines("'latitude': " + str(list(activity['latitude'])) +", \n")
f.writelines("'slope': " + str(list(activity['slope'])) +", \n")
f.writelines("'temperature': " + str(list(activity['temperature'])) +", \n")
f.writelines("'lrbalance': " + str(list(activity['lrbalance'])) +", \n")
f.writelines("'apower': " + str(list(activity['apower'])) +", \n")
f.writelines("'gearratio': " + str(list(activity['gearratio'])) +", \n")
f.writelines("'R_R': " + str(list(activity['R_R'])) +", \n")
f.writelines("'HRV_R-R': " + str(list(activity['HRV_R-R'])) +", \n")
f.writelines("'HRV_R-R flag': " + str(list(activity['HRV_R-R flag'])) +", \n")
f.writelines("}")
f.close()
